# Generated by Django 3.1.1 on 2020-10-19 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0027_attributes'),
        ('engine', '0032_remove_task_z_order'),
    ]

    operations = [
    ]
